version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:PvnjCSjymiigAogMuRdNcjLXKPSEpBuJ@hopper.proxy.rlwy.net:17566/railway
    command: npm run start:dev
